export const Restaurantes = [
  {
    id: 1,
    restrictions: "Vegano",
    name: "Tchê Vegano",
    description: "Loja de produtos veganos.",
    phone: "(54) 991497543",
    whats: "(54) 991497543",
    email: "---",
    site: "https://www.instagram.com/tchevegano/",
    cep: "95034-000",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Pio X",
    street: "Rua Moreira César 2130",
  },
  {
    id: 2,
    restrictions: "Vegano, Celíaco",
    name: "Dolci Vegani",
    description: "Confeitaria vegana.",
    phone: "(54) 99193-5034",
    whats: "(54) 99193-5034",
    email: "---",
    site: "https://www.instagram.com/veganidolci/",
    cep: "95020-370",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Pio X",
    street: "Rua Marechal Floriano, 107",
  },
  {
    id: 3,
    restrictions: "Vegetariano",
    name: "Divina Terra",
    description: "Loja de produtos naturais.",
    phone: "(54) 99349-3620",
    whats: "(54) 99349-3620",
    email: "---",
    site: "https://www.lojadivinaterra.com.br/nossas-lojas/divina-terra-caxias-do-sul/",
    cep: "95020-110",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "São Pelegrino",
    street: "R. Feijó Júnior, 317",
  },
  {
    id: 4,
    restrictions: "Vegano, Celíaco",
    name: "Bugio Eco",
    description: "Pizzaria com opções veganas e sem glúten.",
    phone: "(54) 99143-4977",
    whats: "(54) 99143-4977",
    email: "---",
    site: "https://www.instagram.com/bugio_eco/",
    cep: "94040-000",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "São Pelegrino",
    street: "R. Visc. de Mauá, 390",
  },
  {
    id: 5,
    restrictions: "Vegetariano",
    name: "Gautama",
    description: "Restaurante vegetariano.",
    phone: "(54) 3019-3609",
    whats: "(54) 9165-7856",
    email: "---",
    site: "https://www.facebook.com/restaurantegautama#",
    cep: "95034-160",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "São Pelegrino",
    street: "Rua Feijó Junior, 1137",
  },
  {
    id: 6,
    restrictions: "Vegetariano, Vegano",
    name: "Natureba",
    description: "Restaurante vegetariano.",
    phone: "(54) 3419-5777",
    whats: "---",
    email: "---",
    site: "https://www.instagram.com/restaurantenatureba/",
    cep: "95084-200",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Exposição",
    street: "R. Andrade Neves, 902",
  },
  {
    id: 7,
    restrictions: "Vegetariano",
    name: "Krishna Shankar",
    description: "Restaurante vegetariano.",
    phone: "---",
    whats: "(54) 98126-2947",
    email: "---",
    site: "https://www.instagram.com/krishnashankar2024/",
    cep: "95020-390",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Centro",
    street: "Rua Guia Lopes, 431",
  },
  {
    id: 8,
    restrictions: "Vegetariano, Vegano",
    name: "Ji Xiang",
    description: "Restaurante vegetariano.",
    phone: "(54) 3027-7530",
    whats: "---",
    email: "---",
    site: "https://www.instagram.com/restaurante_jixiang/",
    cep: "95020-460",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Centro",
    street: "R. Alfredo Chaves, 568",
  },
  {
    id: 9,
    restrictions: "Vegetariano, Celíaco",
    name: "Barlavento Rio do Vento",
    description: "Lancheria e sorveteria com opções vegetarianas e sem glúten.",
    phone: "(54) 99908-5500",
    whats: "(54) 99908-5500",
    email: "---",
    site: "https://www.instagram.com/riodovento_barlavento/",
    cep: "95060-000",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Rota do Sol",
    street: "Estrada RSC 453, Km 154",
  },
  {
    id: 10,
    restrictions: "Vegetariano",
    name: "Flor de Cerejeira",
    description: "Restaurante naturalista.",
    phone: "(54) 3533-5300",
    whats: "(54) 3533-5300",
    email: "contato@florrestaurante.com.br",
    site: "https://florrestaurante.com.br/",
    cep: "95020-472",
    uf: "RS",
    city: "Caxias do Sul",
    neighborhood: "Centro",
    street: "R. Os Dezoito do Forte, 1403",
  },
];
