-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "restaurants" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"user_id" bigint NOT NULL,
	"name" varchar(70) NOT NULL,
	"slug" varchar(150) NOT NULL,
	"email" varchar(150),
	"phone" varchar(15),
	"whatsapp" varchar(15),
	"site" varchar(255),
	"description" text,
	"active" boolean DEFAULT true,
	"show_price" boolean DEFAULT true,
	"favorites_count" integer DEFAULT 0,
	"rating_count" integer DEFAULT 0,
	"stars_rating" integer DEFAULT 0,
	"img" varchar(255),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "recipes" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"title" varchar(150) NOT NULL,
	"description" text,
	"img" varchar
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now(),
	"name" varchar,
	"email" varchar,
	"password" varchar,
	"active" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "restrictions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"description" text,
	"icon" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "restaurant_locations" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"restaurant_id" bigint NOT NULL,
	"cep" varchar(15),
	"uf" varchar(2),
	"city" varchar(100),
	"neighborhood" varchar(100),
	"street" varchar(150),
	"number" varchar(20),
	"map_lat" numeric(10, 6),
	"map_lng" numeric(10, 6),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"name" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"password" varchar(255) NOT NULL,
	"role_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recipe_restriction" (
	"recipe_id" bigint NOT NULL,
	"restriction_id" bigint NOT NULL,
	CONSTRAINT "recipe_restriction_pkey" PRIMARY KEY("recipe_id","restriction_id")
);
--> statement-breakpoint
CREATE TABLE "restaurant_restriction" (
	"restaurant_id" bigint NOT NULL,
	"restriction_id" bigint NOT NULL,
	CONSTRAINT "restaurant_restriction_pkey" PRIMARY KEY("restaurant_id","restriction_id")
);
--> statement-breakpoint
ALTER TABLE "restaurants" ADD CONSTRAINT "restaurants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "restaurant_locations" ADD CONSTRAINT "restaurant_locations_restaurant_id_fkey" FOREIGN KEY ("restaurant_id") REFERENCES "public"."restaurants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "fk_role" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recipe_restriction" ADD CONSTRAINT "recipe_restriction_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recipe_restriction" ADD CONSTRAINT "recipe_restriction_restriction_id_fkey" FOREIGN KEY ("restriction_id") REFERENCES "public"."restrictions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "restaurant_restriction" ADD CONSTRAINT "restaurant_restriction_restaurant_id_fkey" FOREIGN KEY ("restaurant_id") REFERENCES "public"."restaurants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "restaurant_restriction" ADD CONSTRAINT "restaurant_restriction_restriction_id_fkey" FOREIGN KEY ("restriction_id") REFERENCES "public"."restrictions"("id") ON DELETE cascade ON UPDATE no action;
*/